// Created by Crowbar 0.63

$ModelName "weapons/tfa_bms/c_bms_357.mdl"

$BodyGroup "studio"
{
	studio "c_bms_357_reference.smd"
}

$Include "c_bms_357_lod.qci"

$SurfaceProp "default"

$Contents "solid"

$IllumPosition 0.786 -0.748 -9.369

$CDMaterials "bms\models\Weapons\V_hand\"
$CDMaterials "bms\models\Weapons\V_357\"

$Attachment "muzzle" "ValveBiped.muzzle" 0 0 0 rotate 0 0 0

$Include "c_bms_357_box.qci"

$Include "c_bms_357_bone.qci"

$Include "c_bms_357_animation.qci"
