// Created by Crowbar 0.58

$ModelName "soldier_stripped.mdl"

$BodyGroup "studio"
{
	studio "soldier_stripped_reference_hd.dmx"
}

$Include "soldier_stripped_lod.qci"

$SurfaceProp "default"

$Contents "solid"

$IllumPosition -0.334 0.595 34.153

$CDMaterials "models\Combine_Soldier\"
$CDMaterials "models\soldier_stripped\"

$Include "soldier_stripped_box.qci"

$Include "soldier_stripped_bone.qci"

$Include "soldier_stripped_animation.qci"
