// Created by Crowbar 0.58

$ModelName "weapons/AR2_shell.mdl"

$BodyGroup "studio"
{
	studio "ar2_shell_reference.smd"
}

$Include "ar2_shell_lod.qci"

$SurfaceProp "default"

$Contents "solid"

$IllumPosition 0.007 0.382 1.385

$CDMaterials "models\Weapons\V_irifle\"

$Include "ar2_shell_box.qci"

$Include "ar2_shell_bone.qci"

$Include "ar2_shell_animation.qci"

$Include "ar2_shell_collision.qci"
