// Created by Crowbar 0.58

$ModelName "weapons/c_ar3.mdl"

$BodyGroup "studio"
{
	studio "c_ar3_v_ar3_bunker_gun01_reference.smd"
}

$Include "c_ar3_lod.qci"

$SurfaceProp "default"

$Contents "solid"

$IllumPosition -1.736 -11.656 -9.388

$CDMaterials "models\weapons\tfa_mmod\v_ar3\"

$Attachment "muzzle" "Base" 1 22 0 rotate 0 90 -180
$Attachment "flashlight" "Base" 1 22 0 rotate 0 0 0
$Include "c_ar3_box.qci"

$Include "c_ar3_bone.qci"

$Include "c_ar3_animation.qci"
