// Created by Crowbar 0.58

$ModelName "Weapons/irifleshell.mdl"

$BodyGroup "studio"
{
	studio "irifleshell.smd"
}

$Include "irifleshell_lod.qci"

$SurfaceProp "default"

$Contents "solid"

$IllumPosition 0.001 0.021 0.646

$CDMaterials "models\Weapons\V_irifle\"

$Include "irifleshell_box.qci"

$Include "irifleshell_bone.qci"

$Include "irifleshell_animation.qci"

$Include "ar2_shell_collision.qci"
