// Created by Crowbar 0.58

$ModelName "shells\shell_57.mdl"

$BodyGroup "studio"
{
	studio "shell_57_57_reference.smd"
}

$Include "shell_57_lod.qci"

$SurfaceProp "shell"

$Contents "solid"

$IllumPosition 0 -0.482 0

$CDMaterials "models\shells\57\"

$Include "shell_57_box.qci"

$Include "shell_57_bone.qci"

$Include "shell_57_animation.qci"

$Include "shell_57_collision.qci"

$keyvalues
{
	prop_data
	{
		base			Metal.Small 
		physicsmode 3
	}
}