// Created by Crowbar 0.58

$ModelName "shells\shell_556.mdl"

$BodyGroup "studio"
{
	studio "shell_556_556_reference.smd"
}

$Include "shell_556_lod.qci"

$SurfaceProp "shell"

$Contents "solid"

$IllumPosition 0 -0.847 0

$CDMaterials "models\shells\556\"

$Include "shell_556_box.qci"

$Include "shell_556_bone.qci"

$Include "shell_556_animation.qci"

$Include "shell_556_collision.qci"

$keyvalues
{
	prop_data
	{
		base			Metal.Small 
		physicsmode 3
	}
}